global:
  image:
    registry: docker.io
    repository: grafana/loki
    tag: 2.9.0
    pullPolicy: IfNotPresent

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
  schemaConfig:
    configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h

  compactor:
    enabled: true
    persistence:
      enabled: true
      size: 10Gi

  distributor:
    enabled: true
    replicas: 2

  ingester:
    enabled: true
    replicas: 2
    persistence:
      enabled: true
      size: 10Gi

  querier:
    enabled: true
    replicas: 2

  queryFrontend:
    enabled: true
    replicas: 2

  queryScheduler:
    enabled: true
    replicas: 2

  ruler:
    enabled: true
    replicas: 2
    persistence:
      enabled: true
      size: 10Gi

  indexGateway:
    enabled: true
    replicas: 2

  serviceMonitor:
    enabled: true
    labels:
      release: prometheus-operator

promtail:
  enabled: true
  config:
    clients:
      - url: http://loki-distributor:3100/loki/api/v1/push
    snippets:
      pipelineStages:
        - docker: {}
      common:
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
