apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-compactor
  labels:
    {{- include "loki.labels" . | nindent 4 }}
    component: compactor
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "loki.selectorLabels" . | nindent 6 }}
      component: compactor
  template:
    metadata:
      labels:
        {{- include "loki.selectorLabels" . | nindent 8 }}
        component: compactor
    spec:
      containers:
        - name: compactor
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          args:
            - "-target=compactor"
            - "-config.file=/etc/loki/loki.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: /var/loki
      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: storage
          persistentVolumeClaim:
            claimName: loki-compactor
