apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-query-scheduler
  labels:
    {{- include "loki.labels" . | nindent 4 }}
    component: query-scheduler
spec:
  replicas: {{ .Values.loki.queryScheduler.replicas }}
  selector:
    matchLabels:
      {{- include "loki.selectorLabels" . | nindent 6 }}
      component: query-scheduler
  template:
    metadata:
      labels:
        {{- include "loki.selectorLabels" . | nindent 8 }}
        component: query-scheduler
    spec:
      containers:
        - name: query-scheduler
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          args:
            - "-target=query-scheduler"
            - "-config.file=/etc/loki/loki.yaml"
          ports:
            - containerPort: 9095
              name: grpc
          volumeMounts:
            - name: config
              mountPath: /etc/loki
      volumes:
        - name: config
          configMap:
            name: loki-config
