apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-query-frontend
  labels:
    {{- include "loki.labels" . | nindent 4 }}
    component: query-frontend
spec:
  replicas: {{ .Values.loki.queryFrontend.replicas }}
  selector:
    matchLabels:
      {{- include "loki.selectorLabels" . | nindent 6 }}
      component: query-frontend
  template:
    metadata:
      labels:
        {{- include "loki.selectorLabels" . | nindent 8 }}
        component: query-frontend
    spec:
      containers:
        - name: query-frontend
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          args:
            - "-target=query-frontend"
            - "-config.file=/etc/loki/loki.yaml"
          ports:
            - containerPort: 3100
              name: http
          volumeMounts:
            - name: config
              mountPath: /etc/loki
      volumes:
        - name: config
          configMap:
            name: loki-config
