apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-ingester
  labels:
    {{- include "loki.labels" . | nindent 4 }}
    component: ingester
spec:
  replicas: {{ .Values.loki.ingester.replicas }}
  selector:
    matchLabels:
      {{- include "loki.selectorLabels" . | nindent 6 }}
      component: ingester
  template:
    metadata:
      labels:
        {{- include "loki.selectorLabels" . | nindent 8 }}
        component: ingester
    spec:
      containers:
        - name: ingester
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          args:
            - "-target=ingester"
            - "-config.file=/etc/loki/loki.yaml"
          ports:
            - containerPort: 3100
              name: http
            - containerPort: 9095
              name: grpc
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: /var/loki
      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: storage
          persistentVolumeClaim:
            claimName: loki-ingester
