{{- /*
  templates/pvc-compactor.yaml
*/ -}}
{{- if and .Values.loki.compactor.enabled .Values.loki.compactor.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-compactor
  labels:
{{ include "loki.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.loki.compactor.persistence.size }}
  storageClassName: {{ .Values.loki.compactor.persistence.storageClass }}
{{- end }}
