apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-ingester
  labels:
    {{- include "loki.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.loki.ingester.persistence.size }}
  storageClassName: {{ .Values.loki.ingester.persistence.storageClass }}
