{{- /*
  templates/pvc-ingester.yaml
*/ -}}
{{- if and .Values.loki.ingester.enabled .Values.loki.ingester.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-ingester
  labels:
{{ include "loki.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.loki.ingester.persistence.size }}
  storageClassName: {{ .Values.loki.ingester.persistence.storageClass }}
{{- end }}
