apiVersion: v1
kind: Service
metadata:
  name: loki-query-scheduler
  labels:
    {{- include "loki.labels" . | nindent 4 }}
    component: query-scheduler
spec:
  ports:
    - name: grpc
      port: 9095
      targetPort: grpc
  selector:
    {{- include "loki.selectorLabels" . | nindent 4 }}
    component: query-scheduler
