apiVersion: v1
kind: Service
metadata:
  name: loki-ingester
  labels:
    {{- include "loki.labels" . | nindent 4 }}
    component: ingester
spec:
  ports:
    - name: http
      port: 3100
      targetPort: http
    - name: grpc
      port: 9095
      targetPort: grpc
  selector:
    {{- include "loki.selectorLabels" . | nindent 4 }}
    component: ingester
