apiVersion: v1
kind: Service
metadata:
  name: loki-query-frontend
  labels:
    {{- include "loki.labels" . | nindent 4 }}
    component: query-frontend
spec:
  ports:
    - name: http
      port: 3100
      targetPort: http
  selector:
    {{- include "loki.selectorLabels" . | nindent 4 }}
    component: query-frontend
