apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-csi
provisioner: ebs.csi.aws.com  # AWS EBS CSI driver
parameters:
  type: gp3
  encrypted: "true"  # Enable encryption (optional)
  kmsKeyId: "arn:aws:kms:us-west-2:123456789012:key/abcd1234..."  # Optional custom KMS key
volumeBindingMode: WaitForFirstConsumer  # Recommended for dynamic provisioning
reclaimPolicy: Delete  # Or Retain if you want to keep volumes after PVC deletion
allowVolumeExpansion: true  # Allow resizing PVCs later
