apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-csi
  labels:
    app.kubernetes.io/name: loki  # Add labels for better tracking
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4  # Explicitly set filesystem type
  encrypted: "true"  # Enable EBS encryption
  # kmsKeyId: "arn:aws:kms:region:account:key/key-id"  # Uncomment if using custom KMS
volumeBindingMode: WaitForFirstConsumer  # Best practice for dynamic provisioning
reclaimPolicy: Delete  # Or 'Retain' to preserve volumes after PVC deletion
allowVolumeExpansion: true  # Allow volume resizing
